image: golang:latest

stages:
  - test
  - build
  - deploy

format:
  stage: test
  when: manual
  script:
    - go fmt ./...
    - go vet ./...
    - go test -race ./...

compile:
  stage: build
  when: manual
  script:
    - make

deploy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  when: manual
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."

