image: golang:latest

stages:
  - build
  - test
  - deploy

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
    GOCACHE: $CI_PROJECT_DIR/.cache
  before_script:
    - mkdir -p .go
    - mkdir -p .cache
  cache:
    paths:
      - .go/pkg/mod/
      - .cache/

build:
  stage: build
  extends: .go-cache
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  script:
    - make

test:
  stage: test
  when: manual # TODO: Enable
  script:
    - go fmt ./...
    - go vet ./...
    - go test -race ./...

deploy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  only:
    - master
  image:
    name: quay.io/podman/stable
  script:
    - podman login -u "${DO_API_TOKEN}" -p "${DO_API_TOKEN}" "registry.digitalocean.com/keibi"
    - podman build -f  docker/DescribeSchedulerDockerfile . -t registry.digitalocean.com/keibi/describe-scheduler:0.0.1
    - podman build -f  docker/DescribeWorkerDockerfile . -t registry.digitalocean.com/keibi/describe-worker:0.0.1
    - podman build -f  docker/OnboardServiceDockerfile . -t registry.digitalocean.com/keibi/onboard-service:0.0.1
    - podman push registry.digitalocean.com/keibi/describe-scheduler:0.0.1
    - podman push registry.digitalocean.com/keibi/describe-worker:0.0.1
    - podman push registry.digitalocean.com/keibi/onboard-service:0.0.1
