basePath: /inventory/api/v1
definitions:
  describe.ApiComplianceReport:
    properties:
      failure_message:
        type: string
      s3_result_url:
        type: string
      status:
        type: string
    type: object
  describe.ApiDescribeResource:
    properties:
      failure_message:
        type: string
      resource_type:
        type: string
      status:
        type: string
    type: object
  describe.ApiDescribeSource:
    properties:
      describe_resource_jobs:
        items:
          $ref: '#/definitions/describe.ApiDescribeResource'
        type: array
      status:
        type: string
    type: object
  describe.ApiSource:
    properties:
      id:
        type: string
      last_compliance_report_at:
        type: string
      last_described_at:
        type: string
      type:
        type: string
    type: object
  inventory.AWSResource:
    properties:
      accountID:
        type: string
      location:
        type: string
      name:
        type: string
      resourceID:
        type: string
      resourceType:
        type: string
    type: object
  inventory.AllResource:
    properties:
      location:
        type: string
      name:
        type: string
      provider:
        type: string
      resourceID:
        type: string
      resourceType:
        type: string
      sourceID:
        type: string
    type: object
  inventory.AzureResource:
    properties:
      location:
        type: string
      name:
        type: string
      resourceGroup:
        type: string
      resourceID:
        type: string
      resourceType:
        type: string
      subscriptionID:
        type: string
    type: object
  inventory.Filters:
    properties:
      keibiSource:
        items:
          type: string
        type: array
      location:
        items:
          type: string
        type: array
      resourceType:
        items:
          type: string
        type: array
    type: object
  inventory.GetAWSResourceResponse:
    properties:
      page:
        $ref: '#/definitions/inventory.Page'
      resources:
        items:
          $ref: '#/definitions/inventory.AWSResource'
        type: array
    type: object
  inventory.GetAzureResourceResponse:
    properties:
      page:
        $ref: '#/definitions/inventory.Page'
      resources:
        items:
          $ref: '#/definitions/inventory.AzureResource'
        type: array
    type: object
  inventory.GetResourcesResponse:
    properties:
      page:
        $ref: '#/definitions/inventory.Page'
      resources:
        items:
          $ref: '#/definitions/inventory.AllResource'
        type: array
    type: object
  inventory.LocationByProviderResponse:
    properties:
      name:
        type: string
    type: object
  inventory.Page:
    properties:
      nextMarker:
        items:
          type: integer
        type: array
      size:
        type: integer
    type: object
  inventory.Sort:
    properties:
      sortBy:
        items:
          $ref: '#/definitions/inventory.SortItem'
        type: array
    type: object
  inventory.SortItem:
    properties:
      direction:
        enum:
        - asc
        - desc
        type: string
      field:
        type: string
    type: object
host: https://dev-cluster.keibi.io
info:
  contact: {}
  description: Inventory service
  title: Inventory Service API
  version: "1.0"
paths:
  /locations/{provider}:
    get:
      description: Getting locations by provider
      parameters:
      - description: Provider
        enum:
        - aws
        - azure
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/inventory.LocationByProviderResponse'
            type: array
      summary: Get locations
      tags:
      - location
  /resource:
    post:
      description: Getting resource details by id and resource type
      parameters:
      - description: Id
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: ResourceType
        in: body
        name: resourceType
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses: {}
      summary: Get details of a Resource
      tags:
      - resource
  /resource_type/{provider}:
    get:
      description: get resource type by provider
      parameters:
      - description: Provider
        enum:
        - aws
        - azure
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: get resource type by provider
      tags:
      - source
  /resources:
    post:
      consumes:
      - application/json
      description: Getting all cloud providers resources by filters
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Page
        in: body
        name: page
        required: true
        schema:
          $ref: '#/definitions/inventory.Page'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/inventory.GetResourcesResponse'
      summary: Get resources
      tags:
      - inventory
  /resources/aws:
    post:
      consumes:
      - application/json
      description: Getting AWS resources by filters
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Page
        in: body
        name: page
        required: true
        schema:
          $ref: '#/definitions/inventory.Page'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/inventory.GetAWSResourceResponse'
      summary: Get AWS resources
      tags:
      - inventory
  /resources/aws/csv:
    post:
      consumes:
      - application/json
      description: Getting AWS resources by filters in csv file
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Get AWS resources in csv file
      tags:
      - inventory
  /resources/azure:
    post:
      consumes:
      - application/json
      description: Getting Azure resources by filters
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Page
        in: body
        name: page
        required: true
        schema:
          $ref: '#/definitions/inventory.Page'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/inventory.GetAzureResourceResponse'
      summary: Get Azure resources
      tags:
      - inventory
  /resources/azure/csv:
    post:
      consumes:
      - application/json
      description: Getting Azure resources by filters in csv file
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Get Azure resources in csv file
      tags:
      - inventory
  /resources/csv:
    post:
      consumes:
      - application/json
      description: Getting all resources by filters in csv file
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Get all resources in csv file
      tags:
      - inventory
  /sources:
    get:
      description: Getting all of Keibi sources
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/describe.ApiSource'
            type: array
      summary: List Sources
      tags:
      - source
  /sources/{source_id}/jobs/compliance:
    get:
      description: List source compliance reports
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/describe.ApiComplianceReport'
            type: array
      summary: List source compliance reports
      tags:
      - source
  /sources/{source_id}/jobs/compliance/refresh:
    get:
      description: Run compliance report jobs
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Run compliance report jobs
      tags:
      - source
  /sources/{source_id}/jobs/describe:
    get:
      description: List source describe jobs
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/describe.ApiDescribeSource'
            type: array
      summary: List source describe jobs
      tags:
      - source
  /sources/{source_id}/jobs/describe/refresh:
    get:
      description: Run describe jobs
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Run describe jobs
      tags:
      - source
  /sources/{source_id}/policy/{policy_id}:
    get:
      description: Assign source to policy
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Assign source to policy
      tags:
      - source
swagger: "2.0"
