definitions:
  api.ComplianceReport:
    properties:
      failureMessage:
        type: string
      s3ResultUrl:
        type: string
      status:
        type: string
    type: object
  api.CreateSourceResponse:
    properties:
      id:
        type: string
    type: object
  api.DescribeResource:
    properties:
      failureMessage:
        type: string
      resourceType:
        type: string
      status:
        type: string
    type: object
  api.DescribeSource:
    properties:
      describeResourceJobs:
        items:
          $ref: '#/definitions/api.DescribeResource'
        type: array
      status:
        type: string
    type: object
  api.DiscoverAWSAccountsResponse:
    properties:
      accountId:
        type: string
      email:
        type: string
      name:
        type: string
      organizationId:
        description: Nil if not part of an AWS organization
        type: string
      status:
        type: string
    type: object
  api.DiscoverAzureSubscriptionsResponse:
    properties:
      id:
        type: string
      name:
        type: string
      status:
        type: string
      subscriptionId:
        type: string
    type: object
  api.Provider:
    properties:
      enabled:
        type: boolean
      id:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  api.SourceConfigAWS:
    properties:
      accessKey:
        type: string
      accountId:
        type: string
      regions:
        items:
          type: string
        type: array
      secretKey:
        type: string
    required:
    - accessKey
    - accountId
    - secretKey
    type: object
  api.SourceConfigAzure:
    properties:
      clientId:
        type: string
      clientSecret:
        type: string
      subscriptionId:
        type: string
      tenantId:
        type: string
    required:
    - clientId
    - clientSecret
    - subscriptionId
    - tenantId
    type: object
  gitlab.com_keibiengine_keibi-engine_pkg_describe_api.Source:
    properties:
      id:
        type: string
      lastComplianceReportAt:
        type: string
      lastDescribedAt:
        type: string
      type:
        type: string
    type: object
  gitlab.com_keibiengine_keibi-engine_pkg_onboard_api.Source:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      sourceId:
        type: string
      type:
        type: string
    type: object
  inventory.AWSResource:
    properties:
      accountID:
        type: string
      location:
        type: string
      name:
        type: string
      resourceID:
        type: string
      resourceType:
        type: string
    type: object
  inventory.AllResource:
    properties:
      location:
        type: string
      name:
        type: string
      provider:
        type: string
      resourceID:
        type: string
      resourceType:
        type: string
      sourceID:
        type: string
    type: object
  inventory.AzureResource:
    properties:
      location:
        type: string
      name:
        type: string
      resourceGroup:
        type: string
      resourceID:
        type: string
      resourceType:
        type: string
      subscriptionID:
        type: string
    type: object
  inventory.Filters:
    properties:
      keibiSource:
        items:
          type: string
        type: array
      location:
        items:
          type: string
        type: array
      resourceType:
        items:
          type: string
        type: array
    type: object
  inventory.GetAWSResourceResponse:
    properties:
      page:
        $ref: '#/definitions/inventory.Page'
      resources:
        items:
          $ref: '#/definitions/inventory.AWSResource'
        type: array
    type: object
  inventory.GetAzureResourceResponse:
    properties:
      page:
        $ref: '#/definitions/inventory.Page'
      resources:
        items:
          $ref: '#/definitions/inventory.AzureResource'
        type: array
    type: object
  inventory.GetResourcesResponse:
    properties:
      page:
        $ref: '#/definitions/inventory.Page'
      resources:
        items:
          $ref: '#/definitions/inventory.AllResource'
        type: array
    type: object
  inventory.LocationByProviderResponse:
    properties:
      name:
        type: string
    type: object
  inventory.Page:
    properties:
      nextMarker:
        items:
          type: integer
        type: array
      size:
        type: integer
    type: object
  inventory.Sort:
    properties:
      sortBy:
        items:
          $ref: '#/definitions/inventory.SortItem'
        type: array
    type: object
  inventory.SortItem:
    properties:
      direction:
        enum:
        - asc
        - desc
        type: string
      field:
        type: string
    type: object
host: dev-cluster.keibi.io
info:
  contact: {}
  title: Keibi Service API
  version: "1.0"
paths:
  /inventory/api/v1/locations/{provider}:
    get:
      description: Getting locations by provider
      parameters:
      - description: Provider
        enum:
        - aws
        - azure
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/inventory.LocationByProviderResponse'
            type: array
      summary: Get locations
      tags:
      - location
  /inventory/api/v1/resource:
    post:
      description: Getting resource details by id and resource type
      parameters:
      - description: Id
        in: body
        name: id
        required: true
        schema:
          type: string
      - description: ResourceType
        in: body
        name: resourceType
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses: {}
      summary: Get details of a Resource
      tags:
      - resource
  /inventory/api/v1/resources:
    post:
      consumes:
      - application/json
      description: Getting all cloud providers resources by filters
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Page
        in: body
        name: page
        required: true
        schema:
          $ref: '#/definitions/inventory.Page'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/inventory.GetResourcesResponse'
      summary: Get resources
      tags:
      - inventory
  /inventory/api/v1/resources/aws:
    post:
      consumes:
      - application/json
      description: Getting AWS resources by filters
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Page
        in: body
        name: page
        required: true
        schema:
          $ref: '#/definitions/inventory.Page'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/inventory.GetAWSResourceResponse'
      summary: Get AWS resources
      tags:
      - inventory
  /inventory/api/v1/resources/aws/csv:
    post:
      consumes:
      - application/json
      description: Getting AWS resources by filters in csv file
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Get AWS resources in csv file
      tags:
      - inventory
  /inventory/api/v1/resources/azure:
    post:
      consumes:
      - application/json
      description: Getting Azure resources by filters
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Page
        in: body
        name: page
        required: true
        schema:
          $ref: '#/definitions/inventory.Page'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/inventory.GetAzureResourceResponse'
      summary: Get Azure resources
      tags:
      - inventory
  /inventory/api/v1/resources/azure/csv:
    post:
      consumes:
      - application/json
      description: Getting Azure resources by filters in csv file
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Get Azure resources in csv file
      tags:
      - inventory
  /inventory/api/v1/resources/csv:
    post:
      consumes:
      - application/json
      description: Getting all resources by filters in csv file
      parameters:
      - description: Filters
        in: body
        name: filters
        required: true
        schema:
          $ref: '#/definitions/inventory.Filters'
      - description: Sort
        in: body
        name: sort
        required: true
        schema:
          $ref: '#/definitions/inventory.Sort'
      produces:
      - text/plain
      responses:
        "200":
          description: ""
      summary: Get all resources in csv file
      tags:
      - inventory
  /onboard/api/v1/{sourceId}:
    delete:
      description: Deleting a single source either AWS / Azure.
      parameters:
      - description: SourceID
        in: path
        name: sourceId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Delete a single source
      tags:
      - onboard
    get:
      description: Returning single source either AWS / Azure.
      parameters:
      - description: SourceID
        in: path
        name: sourceId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gitlab.com_keibiengine_keibi-engine_pkg_onboard_api.Source'
      summary: Returns a single source
      tags:
      - onboard
  /onboard/api/v1/aws:
    post:
      description: Creating AWS source
      parameters:
      - description: name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: description
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: config
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/api.SourceConfigAWS'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CreateSourceResponse'
      summary: Create AWS source
      tags:
      - onboard
  /onboard/api/v1/aws/accounts:
    get:
      description: If the account is part of an organization and the account has premission
        to list the accounts, it will return all the accounts in that organization.
        Otherwise, it will return the single account these credentials belong to.
      parameters:
      - description: AccessKey
        in: body
        name: accessKey
        required: true
        schema:
          type: string
      - description: SecretKey
        in: body
        name: secretKey
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.DiscoverAWSAccountsResponse'
            type: array
      summary: Returns the list of available AWS accounts given the credentials.
      tags:
      - onboard
  /onboard/api/v1/azure:
    post:
      description: Creating Azure source
      parameters:
      - description: name
        in: body
        name: name
        required: true
        schema:
          type: string
      - description: description
        in: body
        name: description
        required: true
        schema:
          type: string
      - description: config
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/api.SourceConfigAzure'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.CreateSourceResponse'
      summary: Create Azure source
      tags:
      - onboard
  /onboard/api/v1/azure/subscriptions:
    get:
      description: Returning the list of available Azure subscriptions.
      parameters:
      - description: TenantId
        in: body
        name: tenantId
        required: true
        schema:
          type: string
      - description: ClientId
        in: body
        name: clientId
        required: true
        schema:
          type: string
      - description: ClientSecret
        in: body
        name: clientSecret
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.DiscoverAzureSubscriptionsResponse'
            type: array
      summary: Returns the list of available Azure subscriptions.
      tags:
      - onboard
  /onboard/api/v1/providers:
    get:
      description: Getting cloud providers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Provider'
            type: array
      summary: Get providers
      tags:
      - onboard
  /onboard/api/v1/sources:
    get:
      description: Returning a list of sources including both AWS and Azure unless
        filtered by Type.
      parameters:
      - description: Type
        enum:
        - aws
        - azure
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/gitlab.com_keibiengine_keibi-engine_pkg_onboard_api.Source'
            type: array
      summary: Returns a list of sources
      tags:
      - onboard
  /schedule/api/v1/resource_type/{provider}:
    get:
      description: get resource type by provider
      parameters:
      - description: Provider
        enum:
        - aws
        - azure
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: get resource type by provider
      tags:
      - schedule
  /schedule/api/v1/sources:
    get:
      description: Getting all of Keibi sources
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/gitlab.com_keibiengine_keibi-engine_pkg_describe_api.Source'
            type: array
      summary: List Sources
      tags:
      - schedule
  /schedule/api/v1/sources/{source_id}/jobs/compliance:
    get:
      description: List source compliance reports
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.ComplianceReport'
            type: array
      summary: List source compliance reports
      tags:
      - schedule
  /schedule/api/v1/sources/{source_id}/jobs/compliance/refresh:
    post:
      description: Run compliance report jobs
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Run compliance report jobs
      tags:
      - schedule
  /schedule/api/v1/sources/{source_id}/jobs/describe:
    get:
      description: List source describe jobs
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.DescribeSource'
            type: array
      summary: List source describe jobs
      tags:
      - schedule
  /schedule/api/v1/sources/{source_id}/jobs/describe/refresh:
    post:
      description: Run describe jobs
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Run describe jobs
      tags:
      - schedule
  /schedule/api/v1/sources/{source_id}/policy/{policy_id}:
    get:
      description: Assign source to policy
      parameters:
      - description: SourceID
        in: path
        name: source_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Assign source to policy
      tags:
      - schedule
schemes:
- https
swagger: "2.0"
